# Generated by Django 4.2.17 on 2025-01-15 06:53

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('realtors', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Listing',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('address', models.CharField(max_length=200)),
                ('street', models.CharField(max_length=200)),
                ('district', models.CharField(choices=[('_', 'All Districts'), ('USA-Las Vegas', 'USA-Las Vegas'), ('USA-New York', 'USA-New York'), ('USA-Los Angeles', 'USA-Los Angeles'), ('USA-Chicago', 'USA-Chicago'), ('USA-San Francisco', 'USA-San Francisco'), ('USA-Miami', 'USA-Miami'), ('USA-Washington D.C.', 'USA-Washington D.C.'), ('USA-Seattle', 'USA-Seattle'), ('UK-London', 'UK-London'), ('France-Paris', 'France-Paris'), ('Italy-Rome', 'Italy-Rome'), ('Spain-Barcelona', 'Spain-Barcelona'), ('Germany-Berlin', 'Germany-Berlin'), ('China-Shanghai', 'China-Shanghai'), ('China-Chengdu', 'China-Chengdu'), ('Hongkong SAR', 'Hongkong SAR'), ('Japan-Kyoto', 'Japan-Kyoto'), ('Korea-Seoul', 'Korea-Seoul')], max_length=50)),
                ('description', models.TextField(blank=True)),
                ('price', models.IntegerField()),
                ('bedrooms', models.CharField(max_length=200)),
                ('bathrooms', models.CharField(max_length=200)),
                ('clubhouse', models.CharField(max_length=200)),
                ('sqft', models.IntegerField()),
                ('estate_size', models.CharField(max_length=200)),
                ('is_published', models.BooleanField(default=True)),
                ('list_date', models.DateTimeField(blank=True, default=datetime.datetime.now)),
                ('photo_main', models.ImageField(upload_to='photos/%Y/%m/%d/')),
                ('photo_1', models.ImageField(blank=True, upload_to='photos/%Y/%m/%d/')),
                ('photo_2', models.ImageField(blank=True, upload_to='photos/%Y/%m/%d/')),
                ('photo_3', models.ImageField(blank=True, upload_to='photos/%Y/%m/%d/')),
                ('photo_4', models.ImageField(blank=True, upload_to='photos/%Y/%m/%d/')),
                ('photo_5', models.ImageField(blank=True, upload_to='photos/%Y/%m/%d/')),
                ('photo_6', models.ImageField(blank=True, upload_to='photos/%Y/%m/%d/')),
                ('realtor', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='realtors.realtor')),
            ],
        ),
    ]
